Paps/Areas/Systems/Controllers/ManualSyncController.cs
using System;
using System.Configuration;
using System.Diagnostics;
using System.Web.Configuration;
using System.Web.Mvc;
using FluentScheduler;

namespace Paps.Areas.Systems.Controllers
{
    public class ManualSyncController : Controller
    {
        // GET: Systems/ManualSync
        public ActionResult Index()
        {
            ViewBag.Path = ConfigurationManager.AppSettings["SyncPath"];

            return View();
        }

        /// <summary>
        /// 手动同步组织机构数据
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        [HttpGet]
        public bool Sync(string path)
        {
            JobManager.Initialize(new SyncStructure(true));
            return true;
        }
    }
}

Paps/Areas/Systems/Views/ManualSync/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}

<div class="col-sm-12">
    <!-- TABLE STRIPED -->
    <div class="panel" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">同步组织机构数据</h3>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @using (Html.BeginForm("Sync", "ManualSync", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    @*<div class="form-group">
                        <label class="control-label col-sm-2">同步程序路径</label>
                        <div class="col-sm-10">
                            <input type="text" name="path" class="form-control" required="required" id="path" value="@ViewBag.Path" />
                        </div>
                    </div>*@
                    <input class="btn btn-primary" value="同 步" type="button" onclick="cl()" />
                }
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    function cl() {
        //        layer.load(0);
        $.get('Sync?path=' + $("#path").val(),
            null,
            function(res) {
                layer.msg('同步程序已经手动开启，同步过程可能需要很长的一段时间，请过段时间再去查看。',
                    { time: 5000 },
                    function() {
                        layer.closeAll();
                    });
            });
    }
</script>