Paps/Controllers/UserController.cs
using DAL;
using Model;
using Paps.Common;
using Paps.Models;
using System;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;

namespace Paps.Controllers
{
    public class UserController : Controller
    {
        Cache data = new Cache();

        // GET: Login
        public ActionResult Index()
        {
            var session = Request.QueryString["sessionid"] ?? "";
            var fromUrl = Request.UrlReferrer == null ? "" : Request.UrlReferrer.ToString();
            
            using (var db = new PapsEntities())
            {
                var tokenUrls = "";
                var loginUrls = "";
                var appID = "";
                var appSecret = "";
                if (fromUrl.ToLower().Contains("rails"))    // 这里加上大铁或者地方铁路来源url   //地方铁路
                {
                    var sysAccess = db.SysAccess.FirstOrDefault(s => s.ID == 2);
                    appID = sysAccess.AppID;
                    appSecret = sysAccess.AppSecret;
                    tokenUrls = ConfigurationManager.AppSettings["railTokenUrls"];
                    loginUrls = ConfigurationManager.AppSettings["railLoginUserUrls"];
                }
                else  //默认大铁
                {
                    var sysAccess = db.SysAccess.FirstOrDefault();
                    appID = sysAccess.AppID;
                    appSecret = sysAccess.AppSecret;
                    tokenUrls = ConfigurationManager.AppSettings["tokenUrls"];
                    loginUrls = ConfigurationManager.AppSettings["loginUserUrls"];
                }
                tokenUrls = tokenUrls + "?appid=" + appID + "&appsecret=" + appSecret;
                var token = LoginServices.GetAccessToken(tokenUrls);
                if (token != "")
                {
                    loginUrls = loginUrls + "?sessionid=" + session + "&token=" + token;

                    var response = LoginServices.GetServiceUser2(loginUrls);
                    //                    var response = LoginServices.TestAccount();
                    if (!string.IsNullOrEmpty(response?.account))
                    {
                        var res = ValidateUser(db, response.account);
                        if (res.status)
                        {

                            Session["UserInfo"] = res.user;
                            Session["UserName"] = res.user.UserName;
                            if (res.user.IsActive == true) TempData["result"] = "IsActive";
                        }
                        return Redirect(res.status ? "/Home/Index" : fromUrl);
                    }
                }
            }
            return View();
        }
        /// <summary>
        /// 登陆按钮
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            return View();
        }
        /// <summary>
        /// 登陆方法
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Login(Users model)
        {
            using (var db = new PapsEntities())
            {
                var password = EncryptHelper.CreateMd5Hash(model.Password); // updated by Ted on 20180522
                var data = ValidateUser(db, model.UserName, password);
                if (data.status)
                {
                    Session["user"] = data.user;
                    if (data.user.RoleId == 1)
                    {
                        return Redirect("/Admin/Home");
                    }
                    else
                    {
                        return Redirect("/Home");
                    }
                }
                else
                {
                    TempData["login"] = "false";
                    return View();
                }
            }
        }
        #region 私有方法
        /// <summary>
        /// 验证用户是否存在
        /// </summary>
        /// <param name="db"></param>
        /// <param name="userName"></param>
        /// <returns></returns>
        private ValidateUserInfo ValidateUser(PapsEntities db, string userName)
        {
            ValidateUserInfo result = new ValidateUserInfo();
            try
            {
                var user = db.Users.FirstOrDefault(p => p.UserName == userName);
                result.status = user != null;
                result.user = user;
            }
            catch (Exception exception)
            {
                result.status = false;
                result.user = null;
            }
            return result;
        }
        /// <summary>
        /// 验证用户是否存在
        /// </summary>
        /// <param name="db"></param>
        /// <param name="userName"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        private ValidateUserInfo ValidateUser(PapsEntities db, string userName, string password)
        {
            ValidateUserInfo result = new ValidateUserInfo();
            try
            {
                var user = db.Users.Where(p => p.UserName == userName && p.Password == password).FirstOrDefault();
                result.status = user == null ? false : true;
                result.user = user;
            }
            catch (Exception ex)
            {
                result.status = false;
                result.user = null;
            }
            return result;
        }
        private ValidateUserInfo AddUser(PapsEntities db, string userName)
        {
            var password = EncryptHelper.CreateMd5Hash("Ht$t1qaz"); // updated by Ted on 20180522
            ValidateUserInfo result = new ValidateUserInfo();
            try
            {
                var entity = new Users();
                entity.UserName = userName;
                entity.Password = password;
                entity.RoleId = 2;
                entity.IsActive = false;
                entity.CreateDate = DateTime.Now;
                db.Users.Add(entity);
                db.SaveChanges();
                result.status = entity.UserId > 0 ? false : true;
                result.user = entity;
            }
            catch (Exception ex)
            {
                result.status = false;
                result.user = null;
            }
            return result;
        }
        #endregion
    }
}

Paps/Views/User/Login.cshtml
@model Model.Users
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>Bootstrap Metro Dashboard by Dennis Ji for ARM demo</title>
    <meta name="description" content="Bootstrap Metro Dashboard">
    <meta name="author" content="Dennis Ji">
    <meta name="keyword" content="Metro, Metro UI, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <!-- end: Meta -->
    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- end: Mobile Specific -->
    <!-- start: CSS -->
    <link id="bootstrap-style" href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link id="base-style" href="~/Content/css/style.css" rel="stylesheet">
    <link id="base-style-responsive" href="~/Content/css/style-responsive.css" rel="stylesheet">
    <!-- end: CSS -->
    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link id="ie-style" href="css/ie.css" rel="stylesheet">
    <![endif]-->
    <!--[if IE 9]>
        <link id="ie9style" href="css/ie9.css" rel="stylesheet">
    <![endif]-->
    <!-- start: Favicon -->
    <link rel="shortcut icon" href="~/Content/img/favicon.ico">
    <!-- end: Favicon -->

    <style type="text/css">
        body {
            background: url(../../Content/img/bg-login.jpg) !important;
        }
    </style>



</head>

<body>
    <div class="container-fluid-full">
        <div class="row-fluid">

            <div class="row-fluid">
                <div class="login-box">
                    <div class="icons">
@*                        <a href="#"><i class="halflings-icon home"></i></a>*@
@*                        <a href="#"><i class="halflings-icon cog"></i></a>*@
                    </div>
                    <h2>隧道人员自动登陆定位系统</h2>

                    @using (Html.BeginForm("Login", "User"))
                    {
                        <fieldset>
                            <div class="input-prepend" title="用户名">
                                <span class="add-on"><i class="halflings-icon user"></i></span>
                                @Html.TextBoxFor(p => p.UserName, new { @class = "input-large span10", @placeholder = "请输入用户名...", })
                                @*<input class="input-large span10" name="username" id="username" type="text" placeholder="请输入用户名..." />*@
                            </div>
                            <div class="clearfix"></div>

                            <div class="input-prepend" title="密码">
                                <span class="add-on"><i class="halflings-icon lock"></i></span>
                                @Html.PasswordFor(p => p.Password, new { @class = "input-large span10", @placeholder = "请输入密码...", })
                                @*<input class="input-large span10" name="password" id="password" type="password" placeholder="请输入密码..." />*@
                            </div>
                            <div class="clearfix"></div>

                            <label class="remember" for="remember"><input type="checkbox" id="remember" />记住密码</label>

                            <div class="button-login">
                                <button type="submit" class="btn btn-primary">登录</button>
                            </div>
                            <div class="clearfix"></div>
                        </fieldset>

                    }
                    <hr>
                    <h3>忘记密码?</h3>
                    <p>
                        <a href="#">点击这里</a> 找回密码.
                    </p>
                </div><!--/span-->
            </div><!--/row-->


        </div><!--/.fluid-container-->

    </div><!--/fluid-row-->
    <div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <ul class="list-inline item-details">
                <li><a href="#">Admin templates</a></li>
                <li><a href="http://themescloud.org">Bootstrap themes</a></li>
            </ul>
        </div>
    </div>
    <!-- start: JavaScript-->

    <!-- end: JavaScript-->

</body>
</html>