Paps/Areas/Systems/Controllers/AdminController.cs
using DAL.Common;
using Model;
using Newtonsoft.Json;
using PagedList;
using Paps.Controllers;
using Paps.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace Paps.Areas.Systems.Controllers
{
    public class AdminController : Controller
    {
        // GET: Systems/Admin
        [BaseController(IsCheck = true)]
        public ActionResult Index()
        {
            ViewBag.TreeView = MenuTreeView();
            return View();
        }
        [HttpPost]
        public ActionResult Index(string Compans)
        {
            try
            {
                using (var db = new PapsEntities())
                {
                    var entity = new Menus();
                    entity.ParentID = 0;
                    entity.Name = Compans;
                    entity.IsDel = false;
                    db.Menus.Add(entity);
                    db.SaveChanges();
                    TempData["result"] = entity.ID > 0 ? "true" : "false";
                }
            }
            catch
            {
                TempData["result"] = "false";
            }
            ViewBag.TreeView = MenuTreeView();
            return View();
        }
        [BaseController(IsCheck = true)]
        public ActionResult List(int page = 1)
        {
            try
            {
                int size = 15;
                using (var db = new PapsEntities())
                {
                    var pageCount = db.Menus.Count(p => p.IsAsync != null);
                    var entity = db.Menus.Where(p => p.IsAsync != null).OrderByDescending(p => p.ID).Take(size).Skip((page - 1) * size).ToList();
                    var pagedlist = new StaticPagedList<Menus>(entity, page, size, pageCount);
                    return View(pagedlist);
                }
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        public ActionResult AddMenu()
        {
            return View();
        }
        [HttpPost]
        public bool AddMenu(string name)
        {
            try
            {
                using (var db = new PapsEntities())
                {
                    var entity = new Menus()
                    {
                        Name = name,
                        IsAsync = true,
                        IsDel = false,
                        ParentID = 0,
                        StructureType = 2//公司
                    };

                    db.Menus.Add(entity);
                    return db.SaveChanges() > 0;
                }
            }
            catch (Exception ex)
            {
                return false;
            }
        }
        [BaseController(IsCheck = true)]
        public ActionResult Add()
        {
            var paras = int.Parse(Request.QueryString["MenuID"]);

            ViewBag.StructureType = Common.DbHelper.GetSingleModel<Menus>(i => i.ID == paras).StructureType;
            ViewBag.Paras = paras;
            return View();
        }
        [HttpPost]
        public ActionResult Add(Menus entity, int paras, int deviceId = 0)
        {
            ViewBag.StructureType = entity.StructureType;
            try
            {
                using (var db = new PapsEntities())
                {
                    var parent = db.Menus.FirstOrDefault(p => p.ID == paras);
                    parent.AccLoginName = "";
                    parent.AccLoginPwd = "";
                    parent.ItemIp = "";
                    parent.ServicePath = "";
                    var pwd = entity.AccLoginPwd == "" ? "" : entity.AccLoginPwd.ToStringEncrypt();
                    var guestPwd = entity.GuestPwd == "" ? "" : entity.GuestPwd.ToStringEncrypt();

                    entity.AccLoginPwd = pwd;
                    entity.GuestPwd = guestPwd;
                    entity.ParentID = paras;
                    entity.ServicePath = "#";//todo
                    if (parent.StructureType == 3)
                    {
                        entity.ServicePath = string.IsNullOrEmpty(entity.ItemIp) ? "#" : "RealTimeWatch?IpAddress=" + entity.ItemIp.ToStringEncrypt();
                    }

                    entity.StructureType = parent.StructureType + 1;
                    db.Menus.Add(entity);
                    db.SaveChanges();//保存之后entity即可获取保存后的数据，例如主键ID
                    var menu = db.Menus.FirstOrDefault(m => m.ID == entity.ID);
                    if (menu != null) menu.PIndex = menu.ID;
                    //var userIdList = db.Roles.Where(i => i.MenuID == Paras).Select(i => i.UserID).ToList();//获取所有拥有该节点权限的用户id，自动赋予他们访问新添加洞口的权限。
                    //userIdList.ForEach(i => { db.Roles.Add(new Roles() { MenuID = entity.ID, UserID = i }); });
                    //db.SaveChanges();
                    var roles = db.RoleMenu.Where(i => i.MenuID == paras || i.MenuID == parent.ID && i.IsChecked == true || i.MenuID == 1).ToList();
                    if (roles.Any())
                    {
                        roles.ForEach(i =>
                        {
                            if (db.RoleMenu.Local.Count(r => r.MenuID == entity.ID && r.MenuName == entity.Name && r.RoleID == i.RoleID) == 0)
                            {
                                db.RoleMenu.Add(new RoleMenu() { MenuID = entity.ID, RoleID = i.RoleID, MenuName = entity.Name });
                            }
                        });
                    }
                    if (parent.StructureType == 3)
                    {
                        //添加菜单和设备之间的映射关系
                        var device = db.Device.FirstOrDefault(d => d.DeviceId == deviceId);
                        if (device != null) device.MenuId = entity.ID;
                        //判断在线率记录中是否有没有映射就已经上线的记录
                        var onlineRecords = db.OnlineRate.Where(o => o.DeviceCode == device.DeviceCode && o.UserId == null).ToList();
                        onlineRecords.ForEach(r =>
                        {
                            r.UserId = entity.ID;
                            r.RegionName = parent.Name;
                            r.PointName = entity.Name;
                        });
                    }
                    db.SaveChanges();

                    TempData["result"] = entity.ID > 0 ? "true" : "false";
                }
            }
            catch (Exception ex)
            {
                TempData["result"] = "false";
            }

            return View();
        }
        [BaseController(IsCheck = true)]
        public ActionResult Edit()
        {
            using (var db = new PapsEntities())
            {
                var paras = Convert.ToInt32(Request.QueryString["MenuID"]);
                var entity = db.Menus.FirstOrDefault(p => p.ID == paras);
                return View(entity);
            }
        }
        [HttpPost]
        public ActionResult Edit(Menus entity)
        {
            try
            {
                using (var db = new PapsEntities())
                {
                    var subItem = db.Menus.Count(p => p.ParentID == entity.ID);
                    ViewBag.IsLastChild = subItem == 0 ? true : false;
                    var model = db.Menus.FirstOrDefault(p => p.ID == entity.ID);
                    var pwd = entity.AccLoginPwd == "" ? "" : entity.AccLoginPwd.ToStringEncrypt();
                    var guestPwd = entity.GuestPwd == "" ? "" : entity.GuestPwd.ToStringEncrypt();
                    if (model.StructureType == 3 && entity.Name != model.Name) //如果修改的是标段级名称
                    {
                        var pointIds = db.Menus.Where(m => m.ParentID == model.ID).Select(m => m.ID).ToList();
                        var onlineDataToEdit = db.OnlineRate.Where(o => o.UserId != null && pointIds.Contains((int)o.UserId)).ToList();
                        onlineDataToEdit.ForEach(e => { e.RegionName = entity.Name; });
                    }

                    if (model.StructureType == 4 && entity.Name != model.Name)
                    {
                        var onlineDataToEdit = db.OnlineRate.Where(o => o.UserId != null && o.UserId == model.ID).ToList();
                        onlineDataToEdit.ForEach(e => { e.PointName = entity.Name; });
                    }
                    model.Name = entity.Name;
                    model.AccLoginName = entity.AccLoginName;
                    model.AccLoginPwd = pwd;
                    model.IsType = entity.IsType;
                    model.IsShowOnline = entity.IsShowOnline;
                    model.DepartmentID = entity.DepartmentID;
                    //2018-8-30新增的客户端普通用户的账号密码Johnson
                    model.GuestUserName = entity.GuestUserName;
                    model.GuestPwd = guestPwd;
                    if (entity.IsType == 0)
                    {
                        model.ItemIp = entity.ItemIp == null ? "" : entity.ItemIp;
                        model.ServicePath = string.IsNullOrEmpty(entity.ItemIp) ? "#" : "RealTimeWatch?IpAddress=" + entity.ItemIp.ToStringEncrypt();
                    }

                    var result = db.SaveChanges();
                    TempData["result"] = result >= 0 ? "true" : "false";
                    return View(model);
                }
            }
            catch
            {
                TempData["result"] = "false";
            }
            return View();
        }
        public static string GetAsyncDate(string departID)
        {
            using (var db = new PapsEntities())
            {
                var entity = db.DepartSync.Where(p => p.DepartID == departID).OrderByDescending(p => p.AsyncDate).FirstOrDefault();
                return entity == null ? "未同步" : entity.AsyncDate.ToString();
            }
        }
        #region Index前端ajax方法，禁用启用
        /// <summary>
        /// 启用
        /// </summary>
        /// <param name="MenuID"></param>

Paps/Areas/Systems/Views/Admin/Add.cshtml
@using DAL.Common
@model Model.Menus
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<div class="col-md-5" style="padding: 20px;">
    @using (Html.BeginForm("Add", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.TextBoxFor(p => p.Name, new { @id = "Name", @required = "required", @placeholder = "请输入组织名称...", @class = "form-control" })
        if (ViewBag.StructureType == 3)
        {
            <div style="margin-left: 20px; margin-bottom: 10px;">
                <label class="radio" style="float: left;">
                    @Html.RadioButtonFor(r => r.IsType, 0, new { @id = "IsType" })固定IP
                </label>
                <label class="radio" style="float: left; margin-left: 30px;">
                    @Html.RadioButtonFor(r => r.IsType, 1, new { @id = "IsType" })不固定IP
                </label>
            </div>
            <br />
            <div class="form-group">
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="deviceKeyWord" placeholder="请输入设备名称" autocomplete="off" />
                    <div id="deviceList" hidden="" style="min-height: 30px; max-height: 150px; overflow-y: scroll;">
                        <ul id="ulDevice" class="list-group"></ul>
                    </div>
                </div>
            </div>
            @Html.TextBoxFor(r => r.ItemIp, new { @id = "ItemIp", @required = "required", @placeholder = "请输入IP地址...", @class = "form-control" })
        }
        <br />
        <input class="btn btn-primary" id="submit" value="保存" type="submit" id="submitForm"/>
        @Html.Hidden("Paras")
        @Html.Hidden("deviceId")
    }
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    var deviceList;
    var deviceId;
    var result = '@Html.Raw(TempData["result"] as string)';
    if (result == "true") {
        layer.msg("添加成功", { time: 1000, area: ['200px', '50px'] }, function () { parent.$.fancybox.close(); });
    } else if (result == "false") {
        layer.msg("添加失败", { time: 1000, area: ['200px', '50px'] }, function () { parent.$.fancybox.close(); });
    }
    $("#deviceKeyWord").on('keyup', function () {
        var val = $("#deviceKeyWord").val();
        $("#ulDevice").empty();
        deviceList.map(function (d) {
            if (d.DeviceName.indexOf(val) >= 0 || d.DeviceCode.indexOf(val) >= 0) {
                $("#ulDevice").append('<li class="list-group-item" data-DeviceId=' + d.DeviceId + '>' + d.DeviceName + '-' + d.DeviceCode + '</li>');
            }
        })
        $("#deviceList").show();
    })
    $("ul#ulDevice").on("click", "li", function (e) {      //只需要找到你点击的是哪个ul里面的就行
        var txt = e.currentTarget.innerText
        $("#deviceKeyWord").val(txt)
        $("#deviceId").val(e.target.dataset.deviceid)
        $("#deviceList").hide();
    });
   
    $("input[name='IsType']").click(function() {
        var v = $("input[name='IsType']:checked").val();
        if (v == '1') {
            $("#ItemIp").attr('disabled', 'disabled');
        } else {
            $("#AccLoginName").removeAttr("required");
            $("#AccLoginPwd").removeAttr("required");
            $("#ItemIp").removeAttr('disabled');
        }
    });
    $(document).ready(function() {
        $("#IsType").val(0);
        $("#existMsg").hide();
        $("#existMsg1").hide();
        $.get('GetDevices', null, function (data) {
            deviceList = data;
        })
    });
</script>

Paps/Areas/Systems/Views/Admin/AddDevice.cshtml
@model Model.Device
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<div class="col-md-6">
    <div class="">
        <div class="panel-heading">
            <h3 class="panel-title">添加新设备</h3>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("AddDevice", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.TextBoxFor(p => p.DeviceName, new { @id = "DeviceName", @required = "required", @placeholder = "请输入设备名称...", @class = "form-control" })
                <br>
                @Html.TextBoxFor(p => p.DeviceCode, new { @id = "DeviceCode", required = "required", @placeholder = "设备唯一编码", @class = "form-control" })
                <br>
                <input class="btn btn-primary" value="保存" type="submit" />
                <input type="hidden" id="result" value="@TempData["result"]" />
                <br />
            }
        </div>
    </div>
</div>

<script src="~/Content/js/jquery-1.9.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        if ($("#result").val() != "") {
            layer.msg("添加成功", { time: 700 }, function () { window.parent.location.reload(); });
        }
    });

</script>

Paps/Areas/Systems/Views/Admin/AddMenu.cshtml
@model Model.Menus
@{
    ViewBag.Title = "AddMenu";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<div style="padding: 20px;">
    <input id="Name" placeholder="请输入公司名称..." class="form-control input-lg" />
    <button type="button" onclick="validate();" class="btn btn-primary btn-block">保 存</button>
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    function validate() {
        if ($("#Name").val() == "") {
            layer.msg('公司名称不能为空', { time: 700 });
        } else {
            $.post("AddMenu", {
                Name: $("#Name").val(), function(res) {
                    window.parent.location.reload();
                }
            });
        }
    }

</script>

Paps/Areas/Systems/Views/Admin/AddRole.cshtml
@model Model.ArrRoles
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<div class="col-md-6">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">添加角色</h3>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("AddRole", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.TextBoxFor(p => p.RoleName, new { @id = "RoleName", @required = "required", @placeholder = "请输入角色名称...", @class = "form-control" })
                <br>
                @Html.TextAreaFor(p => p.Remarks, new { @id = "Remarks", @placeholder = "备注信息", @rows = 4, @class = "form-control", @maxlength = 180 })
                <br>
                <input class="btn btn-primary" value="保存" type="submit" />
                <input type="hidden" id="result" value="@TempData["result"]" />
            }
        </div>
    </div>
</div>

<script src="~/Content/js/jquery-1.9.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        if ($("#result").val() != "") {
            layer.msg("添加成功", { time: 700 }, function () { window.parent.location.reload(); });
        }
    });

</script>

Paps/Areas/Systems/Views/Admin/DeviceManage.cshtml
@model PagedList.StaticPagedList<Model.Device>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "ListRoles";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/FancyBox/jquery.fancybox.css" rel="stylesheet" />
<div class="col-md-12">
    <!-- TABLE STRIPED -->
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">设备管理</h3>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("DeviceManage", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-inline" style="margin-bottom: 10px;">
                    <input type="text" class="form-control" name="keyWord" id="keyWord" value="@ViewData["KeyWord"]" /><input type="submit" class="btn btn-primary" value="搜索" />
                    <a href="#" id="addDevice" class="btn btn-info pull-right"><i class="halflings-icon plus"></i>添加新设备</a>
                </div>
            }
            <table class="table table-striped table-bordered bootstrap-datatable">
                <thead>
                    <tr>
                        <th class="text-center col-md-1">序号</th>
                        <th class="text-center col-md-3">设备名称</th>
                        <th class="text-center">设备编码</th>
                        <th class="text-center col-md-3">操作</th>

                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model != null && Model.Count > 0)
                        {
                            int i = 0;
                            foreach (var item in Model)
                            {
                                i++;
                                <tr>
                                    <td style="text-align: center;">@i</td>
                                    <td style="text-align: center;">@item.DeviceName</td>
                                    <td style="text-align: center;">@item.DeviceCode</td>
                                    <td style="text-align: center;"><a href="#" class="deleteRole btn btn-danger btn-xs" RoleId="@item.DeviceId">删除</a></td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
            <div style="width: 100%;">
                <div style="width: 30%; float: left; height: 80px; line-height: 5em;">
                    共 @Model.PageCount 页
                    第 @Model.PageNumber 页
                    每页 @Model.PageSize 条
                </div>
                <div style="width: 68%; float: left; text-align: right;">
                    @Html.PagedListPager(Model, page => Url.Action("DeviceManage", new { page, keyWord = ViewData["KeyWord"] }))
                </div>
            </div>
        </div>
    </div>
    <!-- END TABLE STRIPED -->
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/jquery.fancybox.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    //    var jq = $.noConflict();
    $(document).ready(function () {
        $("#sbgl").addClass("active");
    });

    $("#addDevice").click(function () {
        $.fancybox({
            width: 620,
            height: '500',
            closeClick: true,
            href: '/Systems/Admin/AddDevice',
            type: "iframe",
            mouseWheel: false,
            afterClose: function () { }
        });
    });


    $(".deleteRole").click(function () {
        var id = $(this).attr('RoleId');
        layer.confirm("确认要删除吗?", { title: "删除确认" }, function (index) {
            layer.close(index);
            $.get("/Systems/admin/DeleteDevice?deviceId=" + id, null, function (data) {
                var msg = "删除" + (data == 'True' ? '成功' : '失败');
                layer.msg(msg, { time: 1000 }, function () { window.parent.location.reload(); });
            });
        });
    });
</script>

Paps/Areas/Systems/Views/Admin/Edit.cshtml
@model Model.Menus
@using DAL.Common;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<style>
    .list-group-item {
        padding: 5px 5px;
    }
</style>
@* 工点信息修改 *@
<div style="padding: 20px;" class="form-horizontal">
    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post))
    {
        @Html.HiddenFor(p => p.ID, new { id = "menuId" })
        <div class="form-group">
            <label class="col-sm-2 control-label">组织名称</label>
            <div class="col-sm-8">
                @Html.TextBoxFor(p => p.Name, new { @id = "Name", @placeholder = "请输入组织名称...", @class = "form-control" })
            </div>
        </div>
        if (Model.StructureType < 4)
        {
            <div class="form-group">
                <label class="control-label col-sm-2">是否显示在线率</label>
                <div class="col-sm-8">
                    @Html.CheckBoxFor(p => p.IsShowOnline, new { @id = "Name", @style = "height: 18px; width: 18px;" })
                </div>
            </div>
        }

        else
        {
            <div class="form-group">
                <span class="control-label col-sm-2">设备名称</span>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="deviceKeyWord" autocomplete="off" />
                    <div id="deviceList" hidden="" style="min-height: 30px; max-height: 150px; overflow-y: scroll;">
                        <ul id="ulDevice" class="list-group"></ul>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">客户机类型</label>
                <div class="controls col-sm-8" style="margin-left: 25px;">
                    <label class="radio">
                        @Html.RadioButtonFor(r => r.IsType, 0, new { @id = "IsType" })固定IP
                    </label>
                    <div style="clear: both"></div>
                    <label class="radio">
                        @Html.RadioButtonFor(r => r.IsType, 1, new { @id = "IsType" })不固定IP
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">IP地址</label>
                <div class="col-sm-8">
                    @Html.TextBoxFor(r => r.ItemIp, new { @id = "ItemIp", @class = "form-control", @placeholder = "请输入IP地址..." })
                </div>
            </div>
        }
        <input class="btn btn-primary" value="修改" type="submit" id="submitForm" />
    }
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    var deviceList;
    var deviceId;
    var result = '@Html.Raw(TempData["result"] as string)';
    if (result == "true") {
        layer.msg("编辑成功", { time: 1000, area: ['200px', '50px'] }, function() { window.parent.location.reload(); });
    } else if (result == "false") {
        layer.msg("编辑失败", { time: 1000, area: ['200px', '50px'] });
    } else if (result == "AccLoginName") {
        layer.msg("标段登陆帐号重复", { time: 1000 });
    }
    $("#deviceKeyWord").on('keyup',
        function() {
            var val = $("#deviceKeyWord").val();
            $("#ulDevice").empty();
            deviceList.map(function(d) {
                if (d.DeviceName.indexOf(val) >= 0 || d.DeviceCode.indexOf(val) >= 0) {
                    $("#ulDevice").append('<li class="list-group-item" data-DeviceId=' + d.DeviceId + '>' + d.DeviceName + '-' + d.DeviceCode + '</li>');
                }
            })
            $("#deviceList").show();
        })
    $("ul#ulDevice").on("click",
        "li",
        function(e) { //只需要找到你点击的是哪个ul里面的就行
            var txt = e.currentTarget.innerText
            $("#deviceKeyWord").val(txt)
            deviceId = e.target.dataset.deviceid
            $("#deviceList").hide();
        });
    $("#submitForm").on('click',
        function() {

            var strType = '@Model.StructureType';
            if (strType < 4) {
                return true;
            } else {

                if (deviceId == undefined) {
                    layer.msg('请先选择一个可用的设备')
                    return false;
                } else {
                    $.get('SetDeviceInfo?deviceId=' + deviceId + '&menuId=' + $("#menuId").val(),
                        null,
                        function(data) {
                            return true;
                        });
                }
            }
        });

    $("input[name='IsType']").click(function() {
        var v = $("input[name='IsType']:checked").val();
        if (v == '1') {
            $("#ItemIp").attr('disabled', 'disabled');
        } else {
            $("#ItemIp").removeAttr('disabled');
        }
    });
    $(document).ready(function() {
        var v = '@Model.IsType';
        if (v == '1') {
            $("#ItemIp").attr('disabled', 'disabled');
        } else {
            $("#ItemIp").removeAttr('disabled');
        }
        $.get('GetDevices', null, function(data) {
            deviceList = data;
            var menuId = $("#menuId").val()
            data.find(function (v, i, a) {
                if (v.MenuId == menuId) {
                    $("#deviceKeyWord").val(v.DeviceName)
                }
            })
        })

    });
</script>

Paps/Areas/Systems/Views/Admin/EditRole.cshtml
@model Model.ArrRoles
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<link href="~/Content/layer/mobile/need/layer.css" rel="stylesheet" />
<div class="col-md-6">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">修改角色</h3>
        </div>
        <div class="panel-body">
            <input type="text" class="form-control" id="roleName" placeholder="角色名称">
            <br>
            <textarea class="form-control" id="remark" placeholder="备注信息" rows="4"></textarea>
            <br>
            <input class="btn btn-primary" value="保存" type="button" onclick="DoSave()" />
            <input type="hidden" id="roleId" />
            <input type="hidden" id="Id" />
            <input type="hidden" id="CreateTime" />
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#roleName").val('@Model.RoleName');
        $("#remark").val('@Model.Remarks');
        $("#Id").val('@Model.ID');
        $("#roleId").val('@Model.RoleID');
        $("#CreateTime").val('@Model.CreateTime');
    });

    function DoSave() {
        if ($("#roleName").val() == '') {
            layer.msg('角色名称不能为空');
        } else {
            $.post("SaveRole",
                { RoleId: $("#roleId").val(), ID: $("#Id").val(), RoleName: $("#roleName").val(), Remarks: $("#remark").val(), CreateTime: $("#CreateTime").val() },
                function(data) {
                    window.parent.location.reload();
                });
        }
    }
</script>

Paps/Areas/Systems/Views/Admin/RoleMenu.cshtml
@{
    ViewBag.Title = "RoleMenu";
    Layout = "~/Areas/Systems/Views/Shared/_Layout.cshtml";
}

<h2>RoleMenu</h2>

Paps/Areas/Systems/Views/Admin/test.cshtml
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}
<div></div>