Paps/Areas/Systems/Controllers/AccessController.cs
using DAL;
using Model;
using Newtonsoft.Json;
using Paps.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TreeView = Model.TreeView;

namespace Paps.Areas.Systems.Controllers
{
    public class AccessController : Controller
    {
        // GET: Systems/Access
        public ActionResult Index()
        {
            using (var db = new PapsEntities())
            {
                var entity = db.SysAccess.ToList();
                if (!entity.Any()) entity = new List<SysAccess>()
                {
                    new SysAccess{ID=0},
                    new SysAccess{ID=1}
                };
                return View(entity);
            }
        }
        [HttpPost]
        public ActionResult Index(List<SysAccess> model)
        {
            try
            {
                using (var db = new PapsEntities())
                {
                    model.ForEach(i =>
                    {
                        var entity = db.SysAccess.FirstOrDefault(p => p.ID == i.ID);
                        if (entity == null)
                        {
                            db.SysAccess.Add(i);
                        }
                        else
                        {
                            entity.AppID = i.AppID;
                            entity.AppSecret = i.AppSecret;
                            entity.ApiKey = i.ApiKey;
                        }

                    });
                    var result = db.SaveChanges();
                    if (result >= 0)
                    {
                        TempData["result"] = "true";
                    }
                    else
                    {
                        TempData["result"] = "false";
                    }
                }
            }
            catch (Exception)
            {
                TempData["result"] = "false";
            }
            return View(model);
        }
        public ActionResult OnlineRate()
        {
            ViewBag.List = "";
            return View();
        }
        /// <summary>
        /// 获取在线率
        /// </summary>
        /// <param name="startTime">开始时间</param>
        /// <param name="endTime">结束时间</param>
        /// <param name="selectNode">部门编号</param>
        /// <param name="workPoint">工点编号</param>
        /// <param name="pointTxt">工点文字模糊搜索</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetOnlineRate(string startTime, string endTime, string selectNode, string workPoint, string pointTxt)
        {
            ViewBag.StartTime = startTime;
            ViewBag.EndTime = endTime;
            ViewBag.WorkPoint = workPoint;
            ViewBag.SelectNode = selectNode;
            ViewBag.PointTxt = pointTxt;
            var listIds = "";
            if (!string.IsNullOrEmpty(workPoint))
            {
                var listId = new List<int> { int.Parse(workPoint) };
                listIds = GetRelatedNodeId(listId, int.Parse(workPoint));
            }
            var list = DatabaseServices.GetOnlineRate(startTime + " 00:00:00", endTime + " 23:59:59", pointTxt, listIds);
            Session["DetailReport"] = list;
            return View("OnlineRate", list);
        }
        //递归获取相关的用户id
        private string GetRelatedNodeId(List<int> listId, int id)
        {
            using (var db = new PapsEntities())
            {
                var list = db.Menus.Where(i => i.ParentID == id).Select(i => i.ID).ToList();
                if (!list.Any()) return string.Join(",", listId);
                list.ForEach(i =>
                {
                    listId.Add(i);
                    GetRelatedNodeId(listId, i);
                }
                );
            }
            return string.Join(",", listId);
        }

        [HttpGet]
        public string GetTree(int isSummary = 0)
        {
            var user = (Users)Session["UserInfo"];
            if (user == null) user = new Users { UserId = 447 };

            var treeViewList = new List<TreeView>();
            using (var db = new PapsEntities())
            {
                var roleUser = db.RoleUser.Where(i => i.UserID == user.UserId).Select(i => i.RoleID).ToList();
                var arrRole = db.ArrRoles.Where(i => roleUser.Contains(i.ID)).Select(i => i.RoleID).ToList();
                var roleMenu = db.RoleMenu.Where(i => arrRole.Contains(i.RoleID)).Select(i => i.MenuID).ToList();
                var topMenus = new List<Menus>();
                if (roleMenu.Contains(1))
                {
                    topMenus = db.Menus.Where(p => p.ParentID == 0 && p.IsDel == false && roleMenu.Contains(p.ID)).ToList(); //有默认控制中心权限
                }
                else
                {
                    topMenus = db.Menus.Where(p => p.ParentID == 1 && p.IsDel == false && roleMenu.Contains(p.ID)).ToList(); //没有默认控制中心权限
                }
                topMenus.ForEach(i => treeViewList.Add(new TreeView() { id = i.ID, text = i.Name, ParentId = 0 }));
                GetTreeView(treeViewList, roleMenu, isSummary);
            }
            return JsonConvert.SerializeObject(treeViewList);
        }

        private static void GetTreeView(List<TreeView> treeViewList, List<int> roleMenus, int isSummary = 0)
        {
            using (var pe = new PapsEntities())
            {
                treeViewList.ForEach(i =>
                {
                    var sonNodes = pe.Menus.Where(j => j.ParentID == i.id && roleMenus.Contains(j.ID)).ToList();
                    if (isSummary != 0) //如果是汇总的话，不显示工点级
                    {
                        sonNodes = sonNodes.Where(j => j.StructureType != 4).ToList();
                    }
                    if (!sonNodes.Any()) return;
                    i.nodes = new List<TreeView>();
                    foreach (var sonNode in sonNodes)
                    {
                        i.nodes.Add(new TreeView()
                        {
                            id = sonNode.ID,
                            text = sonNode.Name,
                            ParentId = sonNode.ParentID
                        });
                    }

                    GetTreeView(i.nodes, roleMenus, isSummary);
                });
            }
        }

        /// <summary>
        /// 汇总报表
        /// </summary>
        public ActionResult SummaryReport()
        {
            ViewBag.List = "";
            return View();
        }
        [HttpPost]
        public ActionResult GetSummaryReport(string startTime, string endTime, string selectNode, string workPoint, string pointTxt)
        {
            ViewBag.StartTime = startTime;
            ViewBag.EndTime = endTime;
            ViewBag.WorkPoint = workPoint;
            ViewBag.SelectNode = selectNode;
            ViewBag.PointTxt = pointTxt;
            var listIds = "";
            if (!string.IsNullOrEmpty(workPoint))
            {
                var listId = new List<int> { int.Parse(workPoint) };
                listIds = GetRelatedNodeId(listId, int.Parse(workPoint));
            }
            var list = DatabaseServices.GetOnlineRate(startTime + " 00:00:00", endTime + " 23:59:59", pointTxt, listIds);
            var model = list.GroupBy(l => l.RegionName);
            var result = model.Select(x =>
            new OnlineRateModel
            {
                RegionName = x.Key,
                PointName = x.Count(y => y.RegionName == x.Key).ToString(),
                OnlineHours = x.Sum(o => o.OnlineHours),
                TotalHours = x.Sum(t => t.TotalHours),
                OnlineRate = Math.Round(x.Sum(o => o.OnlineHours) / x.Sum(t => t.TotalHours) * 100, 2),
                RegionId = x.FirstOrDefault().RegionId
            }).ToList();
            result.Add(new OnlineRateModel()
            {
                RegionName = "总计",
                PointName = result.Sum(i => int.Parse(i.PointName)).ToString(),
                OnlineHours = result.Sum(i => i.OnlineHours),
                TotalHours = result.Sum(i => i.TotalHours),
                OnlineRate = Math.Round(result.Sum(i => i.OnlineHours) / result.Sum(i => i.TotalHours) * 100, 2)
            });
            Session["SummaryReport"] = result;
            return View("SummaryReport", result);
        }

        public ActionResult Detail(string startTime, string endTime, string selectNode, string workPoint,
            string pointTxt)
        {
            var listIds = "";
            if (!string.IsNullOrEmpty(workPoint))
            {
                var listId = new List<int> { int.Parse(workPoint) };
                listIds = GetRelatedNodeId(listId, int.Parse(workPoint));
            }
            var list = DatabaseServices.GetOnlineRate(startTime + " 00:00:00", endTime + " 23:59:59", pointTxt, listIds);
            return View(list);
        }

        public ActionResult ExportSummaryReport()
        {
            var path = Server.MapPath("~/temp/summaryReport.xlsx");
            var list = Session["SummaryReport"] as List<OnlineRateModel>;
            var st = Session["ReportST"].ToString();
            var et = Session["ReportET"].ToString();
            if (list == null)
            {
                ViewBag.List = "no data";
                return View("../Home/OnlineRate");
            }
            ExcelHelper.GenerateSummaryReport(list, path, st, et);
            return File(path, "application/vnd.ms-excel", $"在线率汇总报表_{DateTime.Now:yyyyMMdd}.xlsx");
        }

        public ActionResult ExportDetailReport()
        {
            var path = Server.MapPath("~/temp/detailReport.xlsx");
            var list = Session["DetailReport"] as List<OnlineRateModel>;
            var st = Session["ReportST"].ToString();
            var et = Session["ReportET"].ToString();
            if (list == null)
            {
                ViewBag.List = "no data";
                return View("../Home/OnlineRate");
            }

Paps/Areas/Systems/Views/Access/Detail.cshtml
@model List<Model.OnlineRateModel>
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNoMenu.cshtml";
}
<link href="~/Content/css/jquery.jedate.css" rel="stylesheet" />
<style>
    th {
        text-align: center;
    }
</style>
<div class="col-md-12">
    <!-- TABLE STRIPED -->
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title text-center"><strong>在线率详情报表</strong></h3>
        </div>
        <div class="form-inline text-center">
            <span class="panel-title text-center">统计时间：2018-6-31~2018-7-31</span>
            <span class="panel-title text-center" style="padding-left:50px;">制表时间：2018-7-31 15:03:43</span>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-bordered" style="border-collapse: collapse; text-align: center;">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>所属区域</th>
                        <th>监控点名称</th>
                        <th>在线（小时）</th>
                        <th>应在线（小时）</th>
                        <th>在线率</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        int i = 0;
                        foreach (var m in Model)
                        {
                            <tr>
                                <td>@(Model.IndexOf(m) + 1)</td>
                                <td class="center">@m.RegionName</td>
                                <td class="center">@m.PointName</td>
                                <td class="center">@m.OnlineHours</td>
                                <td class="center">@m.TotalHours</td>
                                <td class="center">@m.OnlineRate%</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/js/bootstrap.js"></script>
<script src="~/Scripts/bootstrap-treeview.min.js"></script>
<script src="~/Scripts/jquery.jedate.min.js"></script>
<script>
    $(document).ready(function () {
        $("#zxltj").addClass("active");
    });
    //日历控件
    var startDate = {
        isinitVal: true,
        initAddVal: [-8],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    var endDate = {
        isinitVal: true,
        initAddVal: [-1],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    $("#startTime").jeDate(startDate);
    $("#endTime").jeDate(endDate);
    $("#removeContent").click(function () {
        $("#selectNode").val('');
        $("#workPoint").val(null);
    });
</script>

Paps/Areas/Systems/Views/Access/ExportExcel.cshtml
<h2>ExportPipeline</h2>

Paps/Areas/Systems/Views/Access/Index.cshtml
@model List<Model.SysAccess>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}

<div class="col-md-6">
    <!-- TABLE STRIPED -->
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">角色管理</h3>
        </div>
        <div class="panel-body">

            @using (Html.BeginForm("Index", "Access", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.HiddenFor(p => p[0].ID)
                @Html.HiddenFor(p => p[1].ID)
                <fieldset>
                    <legend>大铁应用凭证信息</legend>
                    <div class="control-group">
                        <label class="control-label" for="AppID">应用凭证：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(p => p[0].AppID, new { @id = "AppID", @placeholder = "请输入应用凭证...", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="AppSecret">应用密钥：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(r => r[0].AppSecret, new { @id = "AppSecret", @placeholder = "请输入应用密钥...", @class="form-control"})
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="ApiKey">ApiKey：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(r => r[0].ApiKey, new { @id = "ApiKey", @placeholder = "请输入ApiKey...", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset style="margin-top:20px;">
                    <legend>地方铁路应用凭证信息</legend>
                    <div class="control-group">
                        <label class="control-label" for="AppID">应用凭证：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(p => p[1].AppID, new { @id = "AppID", @placeholder = "请输入应用凭证...", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="AppSecret">应用密钥：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(r => r[1].AppSecret, new { @id = "AppSecret", @placeholder = "请输入应用密钥...", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="ApiKey">ApiKey：</label>
                        <div class="controls">
                            <div class="input-append">
                                @Html.TextBoxFor(r => r[1].ApiKey, new { @id = "ApiKey", @placeholder = "请输入ApiKey...", @class = "form-control" })
                            </div>
                        </div>
                    </div>

                </fieldset>
                <div class="control-group" style="margin-top:20px;">
                    <div class="controls">
                        <div class="input-append">
                            <input class="btn btn-primary" value="保 存" type="submit" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Content/js/jquery-1.9.1.min.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#sqxxgl").addClass("active");
    });
    var result = '@Html.Raw(TempData["result"] as string)';
    if (result == "true") {
        layer.msg("保存成功",
            { time: 700 },
            function() {
                window.location.href = "/Systems/Access/Index";
            });
    } else if (result == "false") {
        layer.msg("保存失败");
    }
</script>

Paps/Areas/Systems/Views/Access/OnlineRate.cshtml
@model List<Model.OnlineRateModel>
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}
<link href="~/Content/css/jquery.jedate.css" rel="stylesheet" />
<style>
    th {
        text-align: center;
    }
</style>
<div class="col-md-12">
    <!-- TABLE STRIPED -->
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title text-center"><strong>在线率详情报表</strong></h3>
        </div>
        <div class="form-inline text-center">
            <span class="panel-title text-center">统计时间：2018-6-31~2018-7-31</span>
            <span class="panel-title text-center" style="padding-left:50px;">制表时间：2018-7-31 15:03:43</span>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("GetOnlineRate", "Access", FormMethod.Post, new { id = "frm" }))
            {
                <div style="background-color: rgb(245, 245, 245);margin-left: 0; margin-right: 0;" class="row form-inline">
                    <label for="startTime">开始时间</label>
                    <input id="startTime" readonly="readonly" name="startTime" required="required" type="text" class="jedate" value="@ViewBag.StartTime" style="height: 30px; background-color: white; width: 130px; cursor: pointer;" />
                    <label for="endTime">结束时间</label>
                    <input id="endTime" name="endTime" readonly="readonly" required="required" type="text" style="height: 30px; cursor: pointer; background-color: white; width: 130px;" class="jedate" value="@ViewBag.EndTime" />
                    <span style="font-size: 14px; font-weight: bold;">项目部</span>
                    <div class="input-group">
                        <input type="text" value="@ViewBag.SelectNode" name="selectNode" id="selectNode" readonly="readonly" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 30px; cursor: pointer; background-color: white; width: 200px; text-align: left;">
                        <div id="removeContent" style="cursor: pointer;background: white;border: none;position: absolute;margin-left: 161px;" class="input-group-addon glyphicon glyphicon-remove"></div>
                        <div id="treeview2" class="dropdown-menu" style="min-width: 200px; max-height: 600px; overflow-y: scroll; margin-top: -1px;"></div>
                        <input type="hidden" name="workPoint" id="workPoint" value="@ViewBag.WorkPoint" />
                    </div><!-- /input-group -->
                    <label for="pointTxt">监控点</label>
                    <input type="text" id="pointTxt" value="@ViewBag.PointTxt" style="height: 30px" name="pointTxt" />
                    <button type="submit" class="btn btn-primary">统 计</button>
                    <a id="export" class="btn btn-success pull-right" href="ExportDetailReport">导出</a>
                </div>
                <br />
                <table class="table table-striped table-bordered" style="border-collapse: collapse; text-align: center;">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>所属区域</th>
                            <th>监控点名称</th>
                            <th>在线（小时）</th>
                            <th>应在线（小时）</th>
                            <th>在线率</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            int i = 0;
                            foreach (var m in Model)
                            {
                                <tr>
                                    <td>@(Model.IndexOf(m) + 1)</td>
                                    <td class="center">@m.RegionName</td>
                                    <td class="center">@m.PointName</td>
                                    <td class="center">@m.OnlineHours</td>
                                    <td class="center">@m.TotalHours</td>
                                    <td class="center">@m.OnlineRate%</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/js/bootstrap.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script src="~/Scripts/bootstrap-treeview.min.js"></script>
<script src="~/Scripts/jquery.jedate.min.js"></script>
<script>
    $(document).ready(function () {
        $("#zxltj").addClass("active");
        var list = '@ViewBag.List';
        if (list == 'no data') {
            layer.msg('没有数据，请先统计之后再导出数据！')
        }
    });
    //日历控件
    var startDate = {
        isinitVal: true,
        initAddVal: [-8],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    var endDate = {
        isinitVal: true,
        initAddVal: [-1],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    $("#startTime").jeDate(startDate);
    $("#endTime").jeDate(endDate);
    $("#removeContent").click(function () {
        $("#selectNode").val('');
        $("#workPoint").val(null);
    });
    $(document).ready(function () {
        $.get("/Access/GetTree", null, function (data) {
            var defaultData1 = $.parseJSON(data);
            $('#treeview2').treeview({
                data: defaultData1,
                levels: 2,
                onNodeSelected: function (event, node) {
                    $("#selectNode").val(node.text);
                    $("#workPoint").val(node.id);
                    $("#selectNode").click();
                }
            });
        });
    });
    $("#selectNode").on('click', function (event) {
        event.stopPropagation();
        $("#treeview2").toggle();
    })

</script>

Paps/Areas/Systems/Views/Access/SummaryReport.cshtml
@model List<Model.OnlineRateModel>
@{
    Layout = "~/Areas/Systems/Views/Shared/_LayoutNew.cshtml";
}
<link href="~/Content/css/jquery.jedate.css" rel="stylesheet" />
<style>
    th {
        text-align: center;
    }
</style>
<div class="col-md-12">
    <!-- TABLE STRIPED -->
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title text-center"><strong>在线率汇总报表</strong></h3>
        </div>
        <div class="form-inline text-center">
            <span class="panel-title text-center">统计时间：2018-6-31~2018-7-31</span>
            <span class="panel-title text-center" style="padding-left:50px;">制表时间：2018-7-31 15:03:43</span>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("GetSummaryReport", "Access", FormMethod.Post, new { id = "frm" }))
            {
                <div style="background-color: rgb(245, 245, 245);margin-left: 0; margin-right: 0;" class="row form-inline">
                    <label for="startTime">开始时间</label>
                    <input id="startTime" readonly="readonly" name="startTime" required="required" type="text" class="jedate" value="@ViewBag.StartTime" style="height: 30px; background-color: white; width: 130px; cursor: pointer;" />
                    <label for="endTime">结束时间</label>
                    <input id="endTime" name="endTime" readonly="readonly" required="required" type="text" style="height: 30px; cursor: pointer; background-color: white; width: 130px;" class="jedate" value="@ViewBag.EndTime" />
                    <span style="font-size: 14px; font-weight: bold;">项目部</span>
                    <div class="input-group">
                        <input type="text" value="@ViewBag.SelectNode" name="selectNode" id="selectNode" readonly="readonly" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 30px; cursor: pointer; background-color: white; width: 200px; text-align: left;">
                        <div id="removeContent" style="cursor: pointer;background: white;border: none;position: absolute;margin-left: 161px;" class="input-group-addon glyphicon glyphicon-remove"></div>
                        <div id="treeview2" class="dropdown-menu" style="min-width: 200px; max-height: 600px; overflow-y: scroll; margin-top: -1px;"></div>
                        <input type="hidden" name="workPoint" id="workPoint" value="@ViewBag.WorkPoint" />
                    </div><!-- /input-group -->
                    <label for="pointTxt">监控点</label>
                    <input type="text" id="pointTxt" value="@ViewBag.PointTxt" style="height: 30px" name="pointTxt" />
                    <button type="submit" class="btn btn-primary">统 计</button>
                    <a id="export" class="btn btn-success pull-right" href="ExportSummaryReport">导出</a>
                </div>
                <br />
                <table class="table table-striped table-bordered" style="border-collapse: collapse; text-align: center;">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>所属区域</th>
                            <th>工点数</th>
                            <th>在线（小时）</th>
                            <th>应在线（小时）</th>
                            <th>在线率</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            int i = 0;
                            foreach (var m in Model)
                            {
                                <tr>
                                    <td>@(Model.IndexOf(m) + 1)</td>
                                    <td class="center">@m.RegionName</td>
                                    <td class="center">@m.PointName</td>
                                    <td class="center">@m.OnlineHours</td>
                                    <td class="center">@m.TotalHours</td>
                                    <td class="center"><a href="#" onclick="showDetail(@m.RegionId)">@m.OnlineRate%</a></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Content/js/bootstrap.js"></script>
<script src="~/Scripts/jquery.fancybox.js"></script>
<script src="~/Content/layui/lay/modules/layer.js"></script>
<script src="~/Scripts/bootstrap-treeview.min.js"></script>
<script src="~/Scripts/jquery.jedate.min.js"></script>
<script>
    $(document).ready(function () {
        $("#zxlhz").addClass("active");
        var list = '@ViewBag.List';
        if (list == 'no data') {
            layer.msg('没有数据，请先统计之后再导出数据！')
        }
    });
    //日历控件
    var startDate = {
        isinitVal: true,
        initAddVal: [-8],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    var endDate = {
        isinitVal: true,
        initAddVal: [-1],
        format: 'YYYY-MM-DD',
        maxDate: $.nowDate(0) //最大日期为当前日期
    };
    $("#startTime").jeDate(startDate);
    $("#endTime").jeDate(endDate);
    $("#removeContent").click(function () {
        $("#selectNode").val('');
        $("#workPoint").val(null);
    });
    $(document).ready(function () {
        $.get("/Access/GetTree", null, function (data) {
            var defaultData1 = $.parseJSON(data);
            $('#treeview2').treeview({
                data: defaultData1,
                levels: 2,
                onNodeSelected: function (event, node) {
                    $("#selectNode").val(node.text);
                    $("#workPoint").val(node.id);
                    $("#selectNode").click();
                }
            });
        });
    });
    $("#selectNode").on('click', function (event) {
        event.stopPropagation();
        $("#treeview2").toggle();
    })
    var showDetail = (id) => {
        if (id != 0) {
            $.fancybox({
                width: '80%',
                height: 70,
                padding: 10,
                closeClick: true,
                href: `Detail?startTime=${$("#startTime").val()}&endTime=${$("#endTime").val()}&workPoint=${id}`,
                type: "iframe",
                mouseWheel: false,
                afterClose: function () { }
            });
        }
    }
</script>